development: &development
  host: localhost:3000
  mail:
    address: smtp.gmail.com
    port: 587
    authentication: plain
    user_name: "" 
    password: ""
    enable_starttls_auto: true
  exception:
    email: ["drianotadao@gmail.com", "saulodasilvasantiago@gmail.com"]
    subject: [EXCEPTIO]

production:
  host: locahost:3000
  mail:
    address: smtp.gmail.com
    port: 587
    authentication: plain
    user_name: ""
    password: ""
    enable_starttls_auto: true
  exception:
    email: ["drianotadao@gmail.com", "saulodasilvasantiago@gmail.com"]
    subject: [EXCEPTION]

test:
  <<: *development